# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/user11/work/test_18/test_18.runs/synth_1/soc_pwm_led_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_param bd.open.in_stealth_mode 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/user11/work/test_18/test_18.cache/wt [current_project]
set_property parent.project_path /home/user11/work/test_18/test_18.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/user11/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/user11/work/ip_repo/myip_pwm_2_1_0
  /home/user11/work/ip_repo/myip_pwm_1_1_0
  /home/user11/work/ip_repo/myip_pwm_1_0
  /home/user11/work/ip_repo/myip_btn_1_0
  /home/user11/work/ip_repo/myip_adc_new_1_0
  /home/user11/work/ip_repo/myip_adc_tap_1_0
  /home/user11/work/ip_repo/myip_adc_1_0
  /home/user11/work/ip_repo/myip_adc_cnt_1_0
  /home/user11/work/ip_repo/myip_adc_joy_1_0
  /home/user11/work/ip_repo/myip_stop_watch_1_0
  /home/user11/work/ip_repo/myip_lcd_1_0
  /home/user11/work/ip_repo/myip_dht11_tap_tap11_1_0
  /home/user11/work/ip_repo/myip_dht11_tap_tap_1_0
  /home/user11/work/ip_repo/myip_dht11tap_1_0
  /home/user11/work/ip_repo/myip_dht11_1_0
  /home/user11/work/ip_repo/myip_dht_1_0
  /home/user11/work/ip_repo/myip_fnd_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/user11/work/test_18/test_18.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/hdl/soc_pwm_led_wrapper.v
add_files /home/user11/work/test_18/test_18.srcs/sources_1/bd/soc_pwm_led/soc_pwm_led.bd
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_proc_sys_reset_0_0/soc_pwm_led_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_proc_sys_reset_0_0/soc_pwm_led_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_clk_wiz_0/soc_pwm_led_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_clk_wiz_0/soc_pwm_led_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_clk_wiz_0/soc_pwm_led_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_microblaze_riscv_0_0/soc_pwm_led_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_microblaze_riscv_0_0/soc_pwm_led_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_lmb_bram_0/soc_pwm_led_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_mdm_1_0/soc_pwm_led_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_mdm_1_0/soc_pwm_led_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_0_0/soc_pwm_led_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_0_0/soc_pwm_led_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_0_0/soc_pwm_led_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_1/bd_e39f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_1/bd_e39f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_2/bd_e39f_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_3/bd_e39f_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_4/bd_e39f_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_5/bd_e39f_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_6/bd_e39f_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_7/bd_e39f_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_8/bd_e39f_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_9/bd_e39f_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_10/bd_e39f_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_11/bd_e39f_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_12/bd_e39f_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_13/bd_e39f_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_14/bd_e39f_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_15/bd_e39f_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_16/bd_e39f_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_20/bd_e39f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_21/bd_e39f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_22/bd_e39f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_23/bd_e39f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_24/bd_e39f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_25/bd_e39f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_26/bd_e39f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_27/bd_e39f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_28/bd_e39f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_29/bd_e39f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_30/bd_e39f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_31/bd_e39f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_33/bd_e39f_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_34/bd_e39f_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_35/bd_e39f_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_36/bd_e39f_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_37/bd_e39f_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_38/bd_e39f_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_40/bd_e39f_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_41/bd_e39f_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_42/bd_e39f_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_43/bd_e39f_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_44/bd_e39f_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_45/bd_e39f_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_47/bd_e39f_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_48/bd_e39f_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_49/bd_e39f_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_50/bd_e39f_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_51/bd_e39f_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_52/bd_e39f_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_54/bd_e39f_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_55/bd_e39f_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_56/bd_e39f_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_57/bd_e39f_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_58/bd_e39f_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_59/bd_e39f_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_61/bd_e39f_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_62/bd_e39f_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_63/bd_e39f_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_64/bd_e39f_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_65/bd_e39f_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_66/bd_e39f_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_68/bd_e39f_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_69/bd_e39f_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_70/bd_e39f_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_71/bd_e39f_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_72/bd_e39f_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_73/bd_e39f_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_75/bd_e39f_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_76/bd_e39f_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_77/bd_e39f_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_78/bd_e39f_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_79/bd_e39f_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_80/bd_e39f_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_82/bd_e39f_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_83/bd_e39f_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_84/bd_e39f_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_85/bd_e39f_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_86/bd_e39f_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/bd_0/ip/ip_87/bd_e39f_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_myip_adc_new_0_0/src/xadc_wiz_1/xadc_wiz_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_myip_adc_new_0_0/src/xadc_wiz_1/xadc_wiz_1.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_1_0/soc_pwm_led_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_1_0/soc_pwm_led_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_uartlite_1_0/soc_pwm_led_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_iic_0_0/soc_pwm_led_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_axi_iic_0_0/soc_pwm_led_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/soc_pwm_led_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_pwm_led/ip/soc_pwm_led_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/user11/work/test_18/test_18.srcs/constrs_1/imports/work/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/user11/work/test_18/test_18.srcs/constrs_1/imports/work/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/user11/work/test_18/test_18.srcs/utils_1/imports/synth_1/ring_counter_led_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_pwm_led_wrapper -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_pwm_led_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file soc_pwm_led_wrapper_utilization_synth.rpt -pb soc_pwm_led_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
