#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Script generated by Vivado on Fri Sep 05 14:10:06 KST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : dht11.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : dht11.sh
#                dht11.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                dht11.sh [-reset_run]
#                dht11.sh [-reset_log]
#                dht11.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'dht11.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname lib_cdc_v1_0_3 -libname proc_sys_reset_v5_0_16 -libname xil_defaultlib -libname microblaze_v11_0_14 -libname microblaze_riscv_v1_0_3 -libname lmb_v10_v3_0_14 -libname lmb_bram_if_cntlr_v4_0_25 -libname blk_mem_gen_v8_4_9 -libname axi_lite_ipif_v3_0_4 -libname mdm_riscv_v1_0_3 -libname lib_pkg_v1_0_4 -libname lib_srl_fifo_v1_0_4 -libname axi_uartlite_v2_0_37 -libname xlconstant_v1_1_9 -libname smartconnect_v1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_33 -libname axi_vip_v1_1_19 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm lib_cdc_v1_0_3 proc_sys_reset_v5_0_16 xil_defaultlib microblaze_v11_0_14 microblaze_riscv_v1_0_3 lmb_v10_v3_0_14 lmb_bram_if_cntlr_v4_0_25 blk_mem_gen_v8_4_9 axi_lite_ipif_v3_0_4 mdm_riscv_v1_0_3 lib_pkg_v1_0_4 lib_srl_fifo_v1_0_4 axi_uartlite_v2_0_37 xlconstant_v1_1_9 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_33 axi_vip_v1_1_19)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "dht11.sh - Script generated by export_simulation (Vivado v2024.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./dht11.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/user11/tools/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "/home/user11/tools/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/user11/tools/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/user11/tools/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/home/user11/tools/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_16 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_proc_sys_reset_0_0/sim/dht11_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_clk_wiz_0/dht11_clk_wiz_0_clk_wiz.v" \
  "../../../bd/dht11/ip/dht11_clk_wiz_0/dht11_clk_wiz_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_14 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/a243/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work microblaze_riscv_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/f9dd/hdl/microblaze_riscv_v1_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_microblaze_riscv_0_0/sim/dht11_microblaze_riscv_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_14 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_dlmb_v10_0/sim/dht11_dlmb_v10_0.vhd" \
  "../../../bd/dht11/ip/dht11_ilmb_v10_0/sim/dht11_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_25 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/73e9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_dlmb_bram_if_cntlr_0/sim/dht11_dlmb_bram_if_cntlr_0.vhd" \
  "../../../bd/dht11/ip/dht11_ilmb_bram_if_cntlr_0/sim/dht11_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_9 $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_lmb_bram_0/sim/dht11_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mdm_riscv_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/d547/hdl/mdm_riscv_v1_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_mdm_1_0/sim/dht11_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_4 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_4 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uartlite_v2_0_37 -V93 $xmvhdl_opts \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/9a87/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_axi_uartlite_0_0/sim/dht11_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_9 $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_0/sim/bd_1d4f_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_1/sim/bd_1d4f_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_2/sim/bd_1d4f_arinsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_3/sim/bd_1d4f_rinsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_4/sim/bd_1d4f_awinsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_5/sim/bd_1d4f_winsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_6/sim/bd_1d4f_binsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_7/sim/bd_1d4f_aroutsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_8/sim/bd_1d4f_routsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_9/sim/bd_1d4f_awoutsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_10/sim/bd_1d4f_woutsw_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_11/sim/bd_1d4f_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_12/sim/bd_1d4f_arni_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_13/sim/bd_1d4f_rni_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_14/sim/bd_1d4f_awni_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_15/sim/bd_1d4f_wni_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_16/sim/bd_1d4f_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_17/sim/bd_1d4f_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_18/sim/bd_1d4f_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_19/sim/bd_1d4f_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_20/sim/bd_1d4f_s00a2s_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_21/sim/bd_1d4f_sarn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_22/sim/bd_1d4f_srn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_23/sim/bd_1d4f_sawn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_24/sim/bd_1d4f_swn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_25/sim/bd_1d4f_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_26/sim/bd_1d4f_m00s2a_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_27/sim/bd_1d4f_m00arn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_28/sim/bd_1d4f_m00rn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_29/sim/bd_1d4f_m00awn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_30/sim/bd_1d4f_m00wn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_31/sim/bd_1d4f_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_32/sim/bd_1d4f_m00e_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_33/sim/bd_1d4f_m01s2a_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_34/sim/bd_1d4f_m01arn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_35/sim/bd_1d4f_m01rn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_36/sim/bd_1d4f_m01awn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_37/sim/bd_1d4f_m01wn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_38/sim/bd_1d4f_m01bn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_39/sim/bd_1d4f_m01e_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_40/sim/bd_1d4f_m02s2a_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_41/sim/bd_1d4f_m02arn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_42/sim/bd_1d4f_m02rn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_43/sim/bd_1d4f_m02awn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_44/sim/bd_1d4f_m02wn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_45/sim/bd_1d4f_m02bn_0.sv" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/ip/ip_46/sim/bd_1d4f_m02e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/bd_0/sim/bd_1d4f.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_33 $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_19 $xmvlog_opts -sv +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../test_18.gen/sources_1/bd/dht11/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/3cbc" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/f0b6/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/0127/hdl/verilog" +incdir+"../../../../test_18.gen/sources_1/bd/dht11/ipshared/ec67/hdl" +incdir+"/home/user11/tools/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/dht11/ip/dht11_axi_smc_0/sim/dht11_axi_smc_0.v" \
  "../../../bd/dht11/ipshared/20b9/hdl/myip_dht11_tap_tap11_slave_lite_v1_0_S00_AXI.v" \
  "../../../bd/dht11/ipshared/20b9/src/clock.v" \
  "../../../bd/dht11/ipshared/20b9/src/countre.v" \
  "../../../bd/dht11/ipshared/20b9/src/test.v" \
  "../../../bd/dht11/ipshared/20b9/hdl/myip_dht11_tap_tap11.v" \
  "../../../bd/dht11/ip/dht11_myip_dht11_tap_tap11_0_0/sim/dht11_myip_dht11_tap_tap11_0_0.v" \
  "../../../bd/dht11/sim/dht11.v" \
  "../../../bd/dht11/ipshared/66e3/hdl/myip_fnd_slave_lite_v1_0_S00_AXI.v" \
  "../../../bd/dht11/ipshared/66e3/src/test_top.v" \
  "../../../bd/dht11/ipshared/66e3/hdl/myip_fnd.v" \
  "../../../bd/dht11/ip/dht11_myip_fnd_0_0/sim/dht11_myip_fnd_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.dht11 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.dht11 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/user11/work/test_18/test_18.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log dht11_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./dht11.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: dht11.sh [-help]\n\
Usage: dht11.sh [-step]\n\
Usage: dht11.sh [-lib_map_path]\n\
Usage: dht11.sh [-reset_run]\n\
Usage: dht11.sh [-reset_log]\n\
Usage: dht11.sh [-keep_index]\n\
Usage: dht11.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
